version: "3.8"

services:

  api:
    build: ./Code/Deployment/api
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build: ./Code/Deployment/app
    ports:
      - "8501:8501"
    restart: unless-stopped
    depends_on:
      - api